# Generated by Django 5.0.7 on 2024-07-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_movie_genre_alter_movie_selectable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='selectable',
        ),
    ]
